export const ALL_BOOKS_REQUEST = 'ALL_BOOKS_REQUEST'
export const ALL_BOOKS_SUCCESS = 'ALL_BOOKS_SUCCESS'
export const ALL_BOOKS_FAIL = 'ALL_BOOKS_FAIL'

export const NEW_BOOK_REQUEST = 'NEW_BOOK_REQUEST'
export const NEW_BOOK_SUCCESS = 'NEW_BOOK_SUCCESS'
export const NEW_BOOK_RESET = 'NEW_BOOK_RESET'
export const NEW_BOOK_FAIL = 'NEW_BOOK_FAIL'


export const IMPORT_BOOK_REQUEST = 'IMPORT_BOOK_REQUEST'
export const IMPORT_BOOK_SUCCESS = 'IMPORT_BOOK_SUCCESS'
export const IMPORT_BOOK_RESET = 'IMPORT_BOOK_RESET'
export const IMPORT_BOOK_FAIL = 'IMPORT_BOOK_FAIL'

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST'
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS'
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL'

export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST'
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS'
export const UPDATE_BOOK_RESET = 'UPDATE_BOOK_RESET'
export const UPDATE_BOOK_FAIL = 'UPDATE_BOOK_FAIL'

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_RESET = 'DELETE_BOOK_RESET'
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL'

export const ADD_BOOK_ACCESSION_REQUEST = 'ADD_BOOK_ACCESSION_REQUEST'
export const ADD_BOOK_ACCESSION_SUCCESS = 'ADD_BOOK_ACCESSION_SUCCESS'
export const ADD_BOOK_ACCESSION_RESET = 'ADD_BOOK_ACCESSION_RESET'
export const ADD_BOOK_ACCESSION_FAIL = 'ADD_BOOK_ACCESSION_FAIL'

export const ACCESSION_BOOK_REQUEST = 'ACCESSION_BOOK_REQUEST'
export const ACCESSION_BOOK_SUCCESS = 'ACCESSION_BOOK_SUCCESS'
export const ACCESSION_BOOK_RESET = 'ACCESSION_BOOK_RESET'
export const ACCESSION_BOOK_FAIL = 'ACCESSION_BOOK_FAIL'

export const ACCESSION_DETAILS_REQUEST = 'ACCESSION_DETAILS_REQUEST'
export const ACCESSION_DETAILS_SUCCESS = 'ACCESSION_DETAILS_SUCCESS'
export const ACCESSION_DETAILS_FAIL = 'ACCESSION_DETAILS_FAIL'

export const EDIT_BOOK_ACCESSION_REQUEST = 'EDIT_BOOK_ACCESSION_REQUEST'
export const EDIT_BOOK_ACCESSION_SUCCESS = 'EDIT_BOOK_ACCESSION_SUCCESS'
export const EDIT_BOOK_ACCESSION_RESET = 'EDIT_BOOK_ACCESSION_RESET'
export const EDIT_BOOK_ACCESSION_FAIL = 'EDIT_BOOK_ACCESSION_FAIL'

export const DELETE_BOOK_ACCESSION_REQUEST = 'DELETE_BOOK_ACCESSION_REQUEST'
export const DELETE_BOOK_ACCESSION_SUCCESS = 'DELETE_BOOK_ACCESSION_SUCCESS'
export const DELETE_BOOK_ACCESSION_RESET = 'DELETE_BOOK_ACCESSION_RESET'
export const DELETE_BOOK_ACCESSION_FAIL = 'DELETE_BOOK_ACCESSION_FAIL'

export const ACCESSION_REPORTS_REQUEST = 'ACCESSION_REPORTS_REQUEST'
export const ACCESSION_REPORTS_SUCCESS = 'ACCESSION_REPORTS_SUCCESS'
export const ACCESSION_REPORTS_FAIL = 'ACCESSION_REPORTS_FAIL'

export const ACCREDITATION_REPORTS_REQUEST = 'ACCREDITATION_REPORTS_REQUEST'
export const ACCREDITATION_REPORTS_SUCCESS = 'ACCREDITATION_REPORTS_SUCCESS'
export const ACCREDITATION_REPORTS_FAIL = 'ACCREDITATION_REPORTS_FAIL'

export const STATISTICAL_REPORTS_REQUEST = 'STATISTICAL_REPORTS_REQUEST'
export const STATISTICAL_REPORTS_SUCCESS = 'STATISTICAL_REPORTS_SUCCESS'
export const STATISTICAL_REPORTS_FAIL = 'STATISTICAL_REPORTS_FAIL'

export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST'
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS'
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'