export const BORROW_BOOK_REQUEST = 'BORROW_BOOK_REQUEST'
export const BORROW_BOOK_SUCCESS = 'BORROW_BOOK_SUCCESS'
export const BORROW_BOOK_RESET = 'BORROW_BOOK_RESET'
export const BORROW_BOOK_FAIL = 'BORROW_BOOK_FAIL'

export const CHECKBORROW_BOOK_REQUEST = 'CHECKBORROW_BOOK_REQUEST'
export const CHECKBORROW_BOOK_SUCCESS = 'CHECKBORROW_BOOK_SUCCESS'
export const CHECKBORROW_BOOK_FAIL = 'CHECKBORROW_BOOK_FAIL'

export const CANCELBORROW_BOOK_REQUEST = 'CANCELBORROW_BOOK_REQUEST'
export const CANCELBORROW_BOOK_SUCCESS = 'CANCELBORROW_BOOK_SUCCESS'
export const CANCELBORROW_BOOK_RESET = 'CANCELBORROW_BOOK_RESET'
export const CANCELBORROW_BOOK_FAIL = 'CANCELBORROW_BOOK_FAIL'

export const CONFIRM_BOOK_REQUEST = 'CONFIRM_BOOK_REQUEST'
export const CONFIRM_BOOK_SUCCESS = 'CONFIRM_BOOK_SUCCESS'
export const CONFIRM_BOOK_RESET = 'CONFIRM_BOOK_RESET'
export const CONFIRM_BOOK_FAIL = 'CONFIRM_BOOK_FAIL'

export const CANCEL_ALL_BORROW_BOOK_REQUEST = 'CANCEL_ALL_BORROW_BOOK_REQUEST'
export const CANCEL_ALL_BORROW_BOOK_SUCCESS = 'CANCEL_ALL_BORROW_BOOK_SUCCESS'
export const CANCEL_ALL_BORROW_BOOK_RESET = 'CANCEL_ALL_BORROW_BOOK_RESET'
export const CANCEL_ALL_BORROW_BOOK_FAIL = 'CANCEL_ALL_BORROW_BOOK_FAIL'

export const BORROWBOOK_LENGTH_REQUEST = 'BORROWBOOK_LENGTH_REQUEST'
export const BORROWBOOK_LENGTH_SUCCESS = 'BORROWBOOK_LENGTH_SUCCESS'
export const BORROWBOOK_LENGTH_FAIL = 'BORROWBOOK_LENGTH_FAIL'

export const BOOK_PENDING_REQUEST = 'BOOK_PENDING_REQUEST'
export const BOOK_PENDING_SUCCESS = 'BOOK_PENDING_SUCCESS'
export const BOOK_PENDING_FAIL = 'BOOK_PENDING_FAIL'

export const USER_PENDING_REQUEST = 'USER_PENDING_REQUEST'
export const USER_PENDING_SUCCESS = 'USER_PENDING_SUCCESS'
export const USER_PENDING_FAIL = 'USER_PENDING_FAIL'

export const GET_BORROWEDBOOKSCHART_REQUEST = 'GET_BORROWEDBOOKSCHART_REQUEST'
export const GET_BORROWEDBOOKSCHART_SUCCESS = 'GET_BORROWEDBOOKSCHART_SUCCESS'
export const GET_BORROWEDBOOKSCHART_FAIL = 'GET_BORROWEDBOOKSCHART_FAIL'

export const GET_SECTIONBORROWEDCHART_REQUEST = 'GET_SECTIONBORROWEDCHART_REQUEST'
export const GET_SECTIONBORROWEDCHART_SUCCESS = 'GET_SECTIONBORROWEDCHART_SUCCESS'
export const GET_SECTIONBORROWEDCHART_FAIL = 'GET_SECTIONBORROWEDCHART_FAIL'

export const GET_BOOKLEADERBOARDS_REQUEST = 'GET_BOOKLEADERBOARDS_REQUEST'
export const GET_BOOKLEADERBOARDS_SUCCESS = 'GET_BOOKLEADERBOARDS_SUCCESS'
export const GET_BOOKLEADERBOARDS_FAIL = 'GET_BOOKLEADERBOARDS_FAIL'

export const GET_BORROWERLEADERBOARDS_REQUEST = 'GET_BORROWERLEADERBOARDS_REQUEST'
export const GET_BORROWERLEADERBOARDS_SUCCESS = 'GET_BORROWERLEADERBOARDS_SUCCESS'
export const GET_BORROWERLEADERBOARDS_FAIL = 'GET_BORROWERLEADERBOARDS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'