export const CHECK_EVALUATION_REQUEST = 'CHECK_EVALUATION_REQUEST'
export const CHECK_EVALUATION_SUCCESS = 'CHECK_EVALUATION_SUCCESS'
export const CHECK_EVALUATION_FAIL = 'CHECK_EVALUATION_FAIL'
export const CHECK_EVALUATION_RESET = 'CHECK_EVALUATION_RESET'

export const ALL_EVALUATION_REQUEST = 'ALL_EVALUATION_REQUEST'
export const ALL_EVALUATION_SUCCESS = 'ALL_EVALUATION_SUCCESS'
export const ALL_EVALUATION_FAIL = 'ALL_EVALUATION_FAIL'

export const LIST_EVALUATION_REQUEST = 'ALL_EVALUATION_REQUEST'
export const LIST_EVALUATION_SUCCESS = 'ALL_EVALUATION_SUCCESS'
export const LIST_EVALUATION_FAIL = 'ALL_EVALUATION_FAIL'

export const NEW_EVALUATION_REQUEST = 'NEW_EVALUATION_REQUEST'
export const NEW_EVALUATION_SUCCESS = 'NEW_EVALUATION_SUCCESS'
export const NEW_EVALUATION_RESET = 'NEW_EVALUATION_RESET'
export const NEW_EVALUATION_FAIL = 'NEW_EVALUATION_FAIL'

export const EDIT_EVALUATION_REQUEST = 'EDIT_EVALUATION_REQUEST'
export const EDIT_EVALUATION_SUCCESS = 'EDIT_EVALUATION_SUCCESS'
export const EDIT_EVALUATION_RESET = 'EDIT_EVALUATION_RESET'
export const EDIT_EVALUATION_FAIL = 'EDIT_EVALUATION_FAIL'

export const DELETE_EVALUATION_REQUEST = 'DELETE_EVALUATION_REQUEST'
export const DELETE_EVALUATION_SUCCESS = 'DELETE_EVALUATION_SUCCESS'
export const DELETE_EVALUATION_RESET = 'DELETE_EVALUATION_RESET'
export const DELETE_EVALUATION_FAIL = 'DELETE_EVALUATION_FAIL'

export const STUDENT_EVALUATION_REQUEST = 'STUDENT_EVALUATION_REQUEST'
export const STUDENT_EVALUATION_SUCCESS = 'STUDENT_EVALUATION_SUCCESS'
export const STUDENT_EVALUATION_RESET = 'STUDENT_EVALUATION_RESET'
export const STUDENT_EVALUATION_FAIL = 'STUDENT_EVALUATION_FAIL'

export const DEACTIVATE_EVALUATION_REQUEST = 'DEACTIVATE_EVALUATION_REQUEST'
export const DEACTIVATE_EVALUATION_SUCCESS = 'DEACTIVATE_EVALUATION_SUCCESS'
export const DEACTIVATE_EVALUATION_RESET = 'DEACTIVATE_EVALUATION_RESET'
export const DEACTIVATE_EVALUATION_FAIL = 'DEACTIVATE_EVALUATION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'