export const ALL_PERSONNELS_REQUEST = 'ALL_PERSONNELS_REQUEST'
export const ALL_PERSONNELS_SUCCESS = 'ALL_PERSONNELS_SUCCESS'
export const ALL_PERSONNELS_FAIL = 'ALL_PERSONNELS_FAIL'

export const NEW_PERSONNEL_REQUEST = 'NEW_PERSONNEL_REQUEST'
export const NEW_PERSONNEL_SUCCESS = 'NEW_PERSONNEL_SUCCESS'
export const NEW_PERSONNEL_RESET = 'NEW_PERSONNEL_RESET'
export const NEW_PERSONNEL_FAIL = 'NEW_PERSONNEL_FAIL'

export const PERSONNEL_DETAILS_REQUEST = 'PERSONNEL_DETAILS_REQUEST'
export const PERSONNEL_DETAILS_SUCCESS = 'PERSONNEL_DETAILS_SUCCESS'
export const PERSONNEL_DETAILS_FAIL = 'PERSONNEL_DETAILS_FAIL'

export const UPDATE_PERSONNEL_REQUEST = 'UPDATE_PERSONNEL_REQUEST'
export const UPDATE_PERSONNEL_SUCCESS = 'UPDATE_PERSONNEL_SUCCESS'
export const UPDATE_PERSONNEL_RESET = 'UPDATE_PERSONNEL_RESET'
export const UPDATE_PERSONNEL_FAIL = 'UPDATE_PERSONNEL_FAIL'

export const DELETE_PERSONNEL_REQUEST = 'DELETE_PERSONNEL_REQUEST'
export const DELETE_PERSONNEL_SUCCESS = 'DELETE_PERSONNEL_SUCCESS'
export const DELETE_PERSONNEL_RESET = 'DELETE_PERSONNEL_RESET'
export const DELETE_PERSONNEL_FAIL = 'DELETE_PERSONNEL_FAIL'

export const ALL_ACTIVESTUDENT_REQUEST = 'ALL_ACTIVESTUDENT_REQUEST'
export const ALL_ACTIVESTUDENT_SUCCESS = 'ALL_ACTIVESTUDENT_SUCCESS'
export const ALL_ACTIVESTUDENT_FAIL = 'ALL_ACTIVESTUDENT_FAIL'

export const ALL_INACTIVESTUDENT_REQUEST = 'ALL_INACTIVESTUDENT_REQUEST'
export const ALL_INACTIVESTUDENT_SUCCESS = 'ALL_INACTIVESTUDENT_SUCCESS'
export const ALL_INACTIVESTUDENT_FAIL = 'ALL_INACTIVESTUDENT_FAIL'

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_RESET = 'UPDATE_STUDENT_RESET'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'

export const APPROVE_STUDENT_REQUEST = 'APPROVE_STUDENT_REQUEST'
export const APPROVE_STUDENT_SUCCESS = 'APPROVE_STUDENT_SUCCESS'
export const APPROVE_STUDENT_RESET = 'APPROVE_STUDENT_RESET'
export const APPROVE_STUDENT_FAIL = 'APPROVE_STUDENT_FAIL'

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_RESET = 'DELETE_STUDENT_RESET'
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL'

export const ALL_BORROW_REQUEST = 'ALL_BORROW_REQUEST'
export const ALL_BORROW_SUCCESS = 'ALL_BORROW_SUCCESS'
export const ALL_BORROW_FAIL = 'ALL_BORROW_FAIL'

export const DECLINE_BORROW_REQUEST = 'DECLINE_BORROW_REQUEST'
export const DECLINE_BORROW_SUCCESS = 'DECLINE_BORROW_SUCCESS'
export const DECLINE_BORROW_FAIL = 'DECLINE_BORROW_FAIL'
export const DECLINE_BORROW_RESET = 'DECLINE_BORROW_RESET'

export const ACCEPT_BORROW_REQUEST = 'ACCEPT_BORROW_REQUEST'
export const ACCEPT_BORROW_SUCCESS = 'ACCEPT_BORROW_SUCCESS'
export const ACCEPT_BORROW_FAIL = 'ACCEPT_BORROW_FAIL'
export const ACCEPT_BORROW_RESET = 'ACCEPT_BORROW_RESET'

export const ALL_BORROWED_REQUEST = 'ALL_BORROWED_REQUEST'
export const ALL_BORROWED_SUCCESS = 'ALL_BORROWED_SUCCESS'
export const ALL_BORROWED_FAIL = 'ALL_BORROWED_FAIL'

export const ACCESSION_BORROWED_REQUEST = 'ACCESSION_BORROWED_REQUEST'
export const ACCESSION_BORROWED_SUCCESS = 'ACCESSION_BORROWED_SUCCESS'
export const ACCESSION_BORROWED_RESET = 'ACCESSION_BORROWED_RESET'
export const ACCESSION_BORROWED_FAIL = 'ACCESSION_BORROWED_FAIL'

export const RETURN_BOOK_REQUEST = 'RETURN_BOOK_REQUEST'
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS'
export const RETURN_BOOK_FAIL = 'RETURN_BOOK_FAIL'
export const RETURN_BOOK_RESET = 'RETURN_BOOK_RESET'

export const RETURNED_BOOKS_REQUEST = 'RETURNED_BOOKS_REQUEST'
export const RETURNED_BOOKS_SUCCESS = 'RETURNED_BOOKS_SUCCESS'
export const RETURNED_BOOKS_FAIL = 'RETURNED_BOOKS_FAIL'

export const DECLINE_BOOK_REQUEST = 'DECLINE_BOOK_REQUEST'
export const DECLINE_BOOK_SUCCESS = 'DECLINE_BOOK_SUCCESS'
export const DECLINE_BOOK_RESET = 'DECLINE_BOOK_RESET'
export const DECLINE_BOOK_FAIL = 'DECLINE_BOOK_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const ALL_HISTORYLOG_REQUEST = 'ALL_HISTORYLOG_REQUEST'
export const ALL_HISTORYLOG_SUCCESS = 'ALL_HISTORYLOG_SUCCESS'
export const ALL_HISTORYLOG_FAIL = 'ALL_HISTORYLOG_FAIL'

export const DELETE_HISTORYLOG_REQUEST = 'DELETE_HISTORYLOG_REQUEST'
export const DELETE_HISTORYLOG_SUCCESS = 'DELETE_HISTORYLOG_SUCCESS'
export const DELETE_HISTORYLOG_RESET = 'DELETE_HISTORYLOG_RESET'
export const DELETE_HISTORYLOG_FAIL = 'DELETE_HISTORYLOG_FAIL'

export const DELETE_ALL_HISTORYLOG_REQUEST = 'DELETE_ALL_HISTORYLOG_REQUEST'
export const DELETE_ALL_HISTORYLOG_SUCCESS = 'DELETE_ALL_HISTORYLOG_SUCCESS'
export const DELETE_ALL_HISTORYLOG_RESET = 'DELETE_ALL_HISTORYLOG_RESET'
export const DELETE_ALL_HISTORYLOG_FAIL = 'DELETE_ALL_HISTORYLOG_FAIL'

export const UPDATE_DUE_DATE_REQUEST = 'UPDATE_DUE_DATE_REQUEST'
export const UPDATE_DUE_DATE_SUCCESS = 'UPDATE_DUE_DATE_SUCCESS'
export const UPDATE_DUE_DATE_RESET = 'UPDATE_DUE_DATE_RESET'
export const UPDATE_DUE_DATE_FAIL = 'UPDATE_DUE_DATE_FAIL'

export const PENATY_CHECK_REQUEST = 'PENATY_CHECK_REQUEST'
export const PENATY_CHECK_SUCCESS = 'PENATY_CHECK_SUCCESS'
export const PENATY_CHECK_FAIL = 'PENATY_CHECK_FAIL'

export const ALL_PENALTIES_REQUEST = 'ALL_PENALTIES_REQUEST'
export const ALL_PENALTIES_SUCCESS = 'ALL_PENALTIES_SUCCESS'
export const ALL_PENALTIES_FAIL = 'ALL_PENALTIES_FAIL'

export const PAID_PENALTIES_REQUEST = 'PAID_PENALTIES_REQUEST'
export const PAID_PENALTIES_SUCCESS = 'PAID_PENALTIES_SUCCESS'
export const PAID_PENALTIES_RESET = 'PAID_PENALTIES_RESET'
export const PAID_PENALTIES_FAIL = 'PAID_PENALTIES_FAIL'

export const COUNTER_HISTORYLOG_REQUEST = 'COUNTER_HISTORYLOG_REQUEST'
export const COUNTER_HISTORYLOG_SUCCESS = 'COUNTER_HISTORYLOG_SUCCESS'
export const COUNTER_HISTORYLOG_FAIL = 'COUNTER_HISTORYLOG_FAIL'

export const SEEN_HISTORYLOG_REQUEST = 'SEEN_HISTORYLOG_REQUEST'
export const SEEN_HISTORYLOG_SUCCESS = 'SEEN_HISTORYLOG_SUCCESS'
export const SEEN_HISTORYLOG_FAIL = 'SEEN_HISTORYLOG_FAIL'
export const SEEN_HISTORYLOG_RESET = 'SEEN_HISTORYLOG_RESET'

export const CHECK_PASSWORD_REQUEST = 'CHECK_PASSWORD_REQUEST'
export const CHECK_PASSWORD_SUCCESS = 'CHECK_PASSWORD_SUCCESS'
export const CHECK_PASSWORD_RESET = 'CHECK_PASSWORD_RESET'
export const CHECK_PASSWORD_FAIL = 'CHECK_PASSWORD_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'