export const ALL_RESEARCHES_REQUEST = 'ALL_RESEARCHES_REQUEST'
export const ALL_RESEARCHES_SUCCESS = 'ALL_RESEARCHES_SUCCESS'
export const ALL_RESEARCHES_FAIL = 'ALL_RESEARCHES_FAIL'

export const NEW_RESEARCH_REQUEST = 'NEW_RESEARCH_REQUEST'
export const NEW_RESEARCH_SUCCESS = 'NEW_RESEARCH_SUCCESS'
export const NEW_RESEARCH_RESET = 'NEW_RESEARCH_RESET'
export const NEW_RESEARCH_FAIL = 'NEW_RESEARCH_FAIL'

export const RESEARCH_DETAILS_REQUEST = 'RESEARCH_DETAILS_REQUEST'
export const RESEARCH_DETAILS_SUCCESS = 'RESEARCH_DETAILS_SUCCESS'
export const RESEARCH_DETAILS_FAIL = 'RESEARCH_DETAILS_FAIL'

export const UPDATE_RESEARCH_REQUEST = 'UPDATE_RESEARCH_REQUEST'
export const UPDATE_RESEARCH_SUCCESS = 'UPDATE_RESEARCH_SUCCESS'
export const UPDATE_RESEARCH_RESET = 'UPDATE_RESEARCH_RESET'
export const UPDATE_RESEARCH_FAIL = 'UPDATE_RESEARCH_FAIL'

export const DELETE_RESEARCH_REQUEST = 'DELETE_RESEARCH_REQUEST'
export const DELETE_RESEARCH_SUCCESS = 'DELETE_RESEARCH_SUCCESS'
export const DELETE_RESEARCH_RESET = 'DELETE_RESEARCH_RESET'
export const DELETE_RESEARCH_FAIL = 'DELETE_RESEARCH_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'