export const GET_STUDENT_REQUEST = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_SUCCESS = 'ALL_STUDENTBOOKS_SUCCESS'
export const GET_STUDENT_FAIL = 'ALL_STUDENTBOOKS_FAIL'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_RESET= 'UPDATE_STUDENT_RESET'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const ALL_STUDENTBOOKS_REQUEST = 'ALL_STUDENTBOOKS_REQUEST'
export const ALL_STUDENTBOOKS_SUCCESS = 'ALL_STUDENTBOOKS_SUCCESS'
export const ALL_STUDENTBOOKS_FAIL = 'ALL_STUDENTBOOKS_FAIL'

export const STUDENTBOOK_DETAILS_REQUEST = 'STUDENTBOOK_DETAILS_REQUEST'
export const STUDENTBOOK_DETAILS_SUCCESS = 'STUDENTBOOK_DETAILS_SUCCESS'
export const STUDENTBOOK_DETAILS_FAIL = 'STUDENTBOOK_DETAILS_FAIL'

export const BORROWBOOK_REQUEST = 'BORROWBOOK_REQUEST'
export const BORROWBOOK_SUCCESS = 'BORROWBOOK_SUCCESS'
export const BORROWBOOK_FAIL = 'BORROWBOOK_FAIL'

export const RETURNEDBOOK_REQUEST = 'RETURNEDBOOK_REQUEST'
export const RETURNEDBOOK_SUCCESS = 'RETURNEDBOOK_SUCCESS'
export const RETURNEDBOOK_FAIL = 'RETURNEDBOOK_FAIL'

export const APPOINTMENTBOOK_REQUEST = 'APPOINTMENTBOOK_REQUEST'
export const APPOINTMENTBOOK_SUCCESS = 'APPOINTMENTBOOK_SUCCESS'
export const APPOINTMENTBOOK_FAIL = 'APPOINTMENTBOOK_FAIL'

export const PENALTYSLIP_REQUEST = 'PENALTYSLIP_REQUEST'
export const PENALTYSLIP_SUCCESS = 'PENALTYSLIP_SUCCESS'
export const PENALTYSLIP_FAIL = 'PENALTYSLIP_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'