export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const USER_ROLE_REQUEST = 'USER_ROLE_REQUEST'
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS'
export const USER_ROLE_FAIL = 'USER_ROLE_FAIL'

export const ALL_NOTIFICATION_REQUEST = 'ALL_NOTIFICATION_REQUEST'
export const ALL_NOTIFICATION_SUCCESS = 'ALL_NOTIFICATION_SUCCESS'
export const ALL_NOTIFICATION_FAIL = 'ALL_NOTIFICATION_FAIL'

export const COUNTER_NOTIFICATION_REQUEST = 'COUNTER_NOTIFICATION_REQUEST'
export const COUNTER_NOTIFICATION_SUCCESS = 'COUNTER_NOTIFICATION_SUCCESS'
export const COUNTER_NOTIFICATION_FAIL = 'COUNTER_NOTIFICATION_FAIL'

export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST'
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS'
export const DELETE_NOTIFICATION_RESET = 'DELETE_NOTIFICATION_RESET'
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL'

export const DELETE_ALL_NOTIFICATION_REQUEST = 'DELETE_ALL_NOTIFICATION_REQUEST'
export const DELETE_ALL_NOTIFICATION_SUCCESS = 'DELETE_ALL_NOTIFICATION_SUCCESS'
export const DELETE_ALL_NOTIFICATION_RESET = 'DELETE_ALL_NOTIFICATION_RESET'
export const DELETE_ALL_NOTIFICATION_FAIL = 'DELETE_ALL_NOTIFICATION_FAIL'

export const SEEN_NOTIFICATION_REQUEST = 'SEEN_NOTIFICATION_REQUEST'
export const SEEN_NOTIFICATION_SUCCESS = 'SEEN_NOTIFICATION_SUCCESS'
export const SEEN_NOTIFICATION_FAIL = 'SEEN_NOTIFICATION_FAIL'
export const SEEN_NOTIFICATION_RESET = 'SEEN_NOTIFICATION_RESET'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_RESET = 'UPDATE_ROLE_RESET'
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL'

export const ACTIVATE_USER_REQUEST = 'ACTIVATE_USER_REQUEST'
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS'
export const ACTIVATE_USER_RESET = 'ACTIVATE_USER_RESET'
export const ACTIVATE_USER_FAIL = 'ACTIVATE_USER_FAIL'

export const DEACTIVATED_USER_REQUEST = 'DEACTIVATED_USER_REQUEST'
export const DEACTIVATED_USER_SUCCESS = 'DEACTIVATED_USER_SUCCESS'
export const DEACTIVATED_USER_RESET = 'DEACTIVATED_USER_RESET'
export const DEACTIVATED_USER_FAIL = 'DEACTIVATED_USER_FAIL'

export const END_TERM_USER_REQUEST = 'END_TERM_USER_REQUEST'
export const END_TERM_USER_SUCCESS = 'END_TERM_USER_SUCCESS'
export const END_TERM_USER_RESET = 'END_TERM_USER_RESET'
export const END_TERM_USER_FAIL = 'END_TERM_USER_FAIL'

export const ALL_FACULTY_REQUEST = 'ALL_FACULTY_REQUEST'
export const ALL_FACULTY_SUCCESS = 'ALL_FACULTY_SUCCESS'
export const ALL_FACULTY_FAIL = 'ALL_FACULTY_FAIL'

export const PENDING_FACULTY_REQUEST = 'PENDING_FACULTY_REQUEST'
export const PENDING_FACULTY_SUCCESS = 'PENDING_FACULTY_SUCCESS'
export const PENDING_FACULTY_FAIL = 'PENDING_FACULTY_FAIL'

export const ACCEPT_FACULTY_REQUEST = 'ACCEPT_FACULTY_REQUEST'
export const ACCEPT_FACULTY_SUCCESS = 'ACCEPT_FACULTY_SUCCESS'
export const ACCEPT_FACULTY_RESET = 'ACCEPT_FACULTY_RESET'
export const ACCEPT_FACULTY_FAIL = 'ACCEPT_FACULTY_FAIL'

export const DECLINE_FACULTY_REQUEST = 'DECLINE_FACULTY_REQUEST'
export const DECLINE_FACULTY_SUCCESS = 'DECLINE_FACULTY_SUCCESS'
export const DECLINE_FACULTY_RESET = 'DECLINE_FACULTY_RESET'
export const DECLINE_FACULTY_FAIL = 'DECLINE_FACULTY_FAIL'

export const DELETE_FACULTY_REQUEST = 'DELETE_FACULTY_REQUEST'
export const DELETE_FACULTY_SUCCESS = 'DELETE_FACULTY_SUCCESS'
export const DELETE_FACULTY_RESET = 'DELETE_FACULTY_RESET'
export const DELETE_FACULTY_FAIL = 'DELETE_FACULTY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'